version: "3.8"

services:
  app:
    build: .
    container_name: "fitness-calculator-container"
    ports:
      - "8080:8080"
    environment:
      DB_URL: 'jdbc:postgresql://db:5432/FitnessCalculator'
      DB_USERNAME: postgres
      DB_PASSWORD: password
    restart: always
    depends_on:
      - db

  db:
    container_name: postgres_container
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: FitnessCalculator
    volumes:
      - pg_db:/data/postgres
    ports:
      - "5432:5432"
    restart: always

volumes:
  pg_db:
